name: region_settings
description: A Flutter plugin to get device region settings such as measurement system, temperature units, and date formats.
version: 1.1.0
repository: https://github.com/ncosgray/region_settings
issue_tracker: https://github.com/ncosgray/region_settings/issues

environment:
  sdk: '>=3.3.4 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.nathanatos.region_settings
        pluginClass: RegionSettingsPlugin
      ios:
        pluginClass: RegionSettingsPlugin
